### ISSUE TITLE
Rich presence timer is incorrect

### ISSUE THREAD

**Issue by Alluysl** [MashMB/sublimecord#1]
Steps to reproduce:
- open Discord
- (possibly required) add Sublime to the Game Activity app list
- open Sublime
- install Sublimecord
- connect to Discord

Expected behavior: the time displayed in the rich presence is the time spent on Sublime or on the chosen file, since it was connected or since Sublime started or since my PC started or since ever.

Actual behavior: displays a time around nineteen hours that doesn't correspond to any combination of the possible expected behaviors: changing files doesn't affect the timer, even if Sublime is restarted, so this can be ruled out, and obviously I have spent less time than 19h on Sublime today or even before installing Sublimecord, and way more than that since I started using Sublime.

The problem persisted through multiple computer restarts.

Things I've tried that didn't fix the issue:
- disconnecting and reconnecting Sublime to Discord
- disconnecting, restarting Sublime, then reconnecting
- closing Sublime without disconnecting, then reopening it and reconnecting
- removing Sublime from the Game Activity app list, disconnecting Sublimecord, then reconnecting

Then again, I could be missing something, but I'm 99% sure this is a bug.

I'm using Discord Canary version 71176 on a Windows 10 Home version 10.0.18363 OS, if that helps.

**Comment by Alluysl** [comment]
The problem could be on Discord's side, I have no idea. I haven't been able to find information on the subject.

**Comment by MashMB** [comment]
Hi,

This small project is not under maintaince any more. There is no a lot of interest on in, as you can see, last commit was pushed in 2018. I will close this issue and turn off issues section.
